/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.theflysong;

import org.joml.Matrix4f;
import org.joml.Vector4f;

import io.github.theflysong.client.gl.Window;
import io.github.theflysong.client.gl.mesh.GLGpuMesh;
import io.github.theflysong.client.gl.mesh.GLVertexLayouts;
import io.github.theflysong.client.gl.shader.GLShaders;
import io.github.theflysong.client.gl.shader.Shader;
import io.github.theflysong.client.render.RenderItem;
import io.github.theflysong.client.render.Renderer;
import io.github.theflysong.client.render.preprocessor.SpriteOverlayPreprocessor;
import io.github.theflysong.client.sprite.Models;
import io.github.theflysong.client.sprite.Sprite;
import io.github.theflysong.client.sprite.Sprites;

import static org.lwjgl.opengl.GL11C.GL_BLEND;
import static org.lwjgl.opengl.GL11C.GL_ONE_MINUS_SRC_ALPHA;
import static org.lwjgl.opengl.GL11C.GL_SRC_ALPHA;
import static org.lwjgl.opengl.GL11C.glBlendFunc;
import static org.lwjgl.opengl.GL11C.glEnable;

import java.util.ArrayList;
import java.util.List;

public class App {
    private static final float WINDOW_WIDTH = 960.0f;
    private static final float WINDOW_HEIGHT = 540.0f;

    private static final class AppState {
        private Renderer renderer;
        private List<RenderItem> renderItems = new ArrayList<>();
    }

    public static void main(String[] args) {
        AppState state = new AppState();

        new Window((int) WINDOW_WIDTH, (int) WINDOW_HEIGHT, "linklink - Gem3 Overlay Demo")
                .onInit(() -> init(state))
                .onRender(() -> render(state))
                .onCleanup(() -> cleanup(state))
                .run();
    }

    private static void init(AppState state) {
        GLVertexLayouts.LAYOUTS.onInitialization();
        Models.initialize();
        GLShaders.SHADERS.onInitialization();
        Sprites.initialize();

        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

        state.renderer = new Renderer();
        float aspect = WINDOW_WIDTH / WINDOW_HEIGHT;
        Matrix4f projection = new Matrix4f().ortho(-aspect, aspect, -1.0f, 1.0f, -1.0f, 1.0f);
        state.renderer.updateProjection(projection);

        Vector4f DIAMOND_COLOR = new Vector4f(0.35f, 0.90f, 1.00f, 1.0f);
        var sprite = Sprites.GEM3.get();

        state.renderItems.add(new RenderItem(
            sprite.model().createGpuMesh(),
            sprite.shader(),
            new Matrix4f().identity(),
            SpriteOverlayPreprocessor.processor(DIAMOND_COLOR, sprite)
        ));
    }

    private static void render(AppState state) {
        for (RenderItem item : state.renderItems) {
            state.renderer.submit(item);
        }
        state.renderer.flush();
    }

    private static void cleanup(AppState state) {
        for (RenderItem item : state.renderItems) {
            if (item.mesh() != null) {
                item.mesh().close();
            }
        }
        Sprites.closeAll();
        Models.closeAll();
        GLShaders.closeAll();
    }
}